name: Add PR Guidelines Comment

on: [pull_request]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for appropriate label
        id: label-check
        run: |
          if [ -z "$(jq -r '.pull_request.labels[] | select(.name == "appropriate-label")' $GITHUB_EVENT_PATH)" ]; then
            echo "No appropriate label found. Adding label."
            gh pr edit ${{ github.event.pull_request.number }} --add-label "appropriate-label"
          fi

      - name: Set failure if label not found
        if: steps.label-check.outputs.label-found == 'false'
        run: |
          echo "No appropriate GitHub label found in the PR. Failing the job."
          exit 1
