name: Merge Rule Deploy

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    env: 
      DR_KIBANA_URL: ${{ secrets.DR_KIBANA_URL }}
      DR_KIBANA_USER: ${{ secrets.DR_KIBANA_USER }}
      DR_KIBANA_PASSWORD: ${{ secrets.DR_KIBANA_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge
        pip install .[dev]

    - name: Python Lint
      run: |
        python -m flake8 tests detection_rules --ignore D203,N815 --max-line-length 120
        #python -m flake8 tests detection_rules --ignore D203 --max-line-length 120

    - name: Deploy Rules
      run: |
        python update_rules.py
