name: PR Rule Tests

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Create requirements.txt
      run: |
        cat <<EOF > requirements.txt
        eql
        pytoml
        requests
        pyyaml
        click
        pyflakes
        flake8
        pep8-naming
        pytest>=3.6
        jsonschema==3.2.0
        marshmallow-jsonschema~=0.12.0
        EOF

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt 

    #- name: Python Lint
      #run: |
        #python -m flake8 tests detection_rules --ignore D203 --max-line-length 120

    - name: Unit tests
      run: |
        python -m detection_rules test

    - name: Clean up Git configuration
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
