name: PR Rule Tests

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge
        python install .[dev] 

    - name: Python Lint
      run: |
        #python -m flake8 tests detection_rules --ignore D203 --max-line-length 120
        python -m flake8 tests detection_rules --ignore D203,N815 --max-line-length 120

    - name: Python License Check
      run: |
        python -m detection_rules dev license-check

    - name: Unit tests
      run: |
        python -m detection_rules test

    - name: Clean up Git configuration
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
